### ISSUE TITLE
path finding breaks on arrays with objects

### ISSUE THREAD

**Issue by ulfox** [ulfox/dby#17]
**Describe the bug**
GetFirst & Get return key not found on arrays with maps

**To Reproduce**

Example yaml that causes GetFirst, Get  to exit with no key was found
```yaml

key-1:
    - key-2 : 
        - key-3: v3
    - key-4:
        - key-5: v5
```
**Expected behaviour**

Queries on key-{1,2,3,4,5} should return a value
